name: kasir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0-218.1.beta <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  introduction_screen: ^3.1.11
  lottie: 1.1.0
  flutter:
    sdk: flutter
  eva_icons_flutter: ^3.1.0
  badges: ^2.0.3
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/lottie/
  uses-material-design: true
